### ISSUE TITLE
While creating Issue from webform with the customer login, showing error

### ISSUE THREAD

**Issue by vinod-8848digital** [8848digital/erpnext#195]
### Information about bug

**Information about the bug**

- Create a user and give the role as customer,
- login with the newly created user,
- after login click on home,
- Click on Issue label at top right it will be there,
- After clicking on the issue, a new issue web form will get opened,
- In the web form click the button new,
- After clicking on the new button, it will open a new issue with the fields,
- fill the details and click on submit button at bottom right
![Screenshot from 2024-10-08 15-09-39](https://github.com/user-attachments/assets/ada0fda5-d5b4-4d27-bed6-138c5e64d82e)

![Screenshot from 2024-10-08 15-10-12](https://github.com/user-attachments/assets/85db5fb4-3000-4bfe-af14-70a5098aa8ed)

![Screenshot from 2024-10-08 15-10-48](https://github.com/user-attachments/assets/6d72fefa-2305-4452-9efa-7a9d4317c290)

**TraceBack**
website.js:183 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/rate_limiter.py", line 154, in wrapper
    return fn(*args, **kwargs)
  File "apps/payments/payments/overrides/payment_webform.py", line 119, in accept
    doc.insert(ignore_permissions=True, ignore_mandatory=ignore_mandatory)
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1306, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/erpnext/erpnext/support/doctype/service_level_agreement/service_level_agreement.py", line 511, in apply
    process_sla(doc, sla)
  File "apps/erpnext/erpnext/support/doctype/service_level_agreement/service_level_agreement.py", line 530, in process_sla
    update_response_and_resolution_metrics(doc, sla.apply_sla_for_resolution)
  File "apps/erpnext/erpnext/support/doctype/service_level_agreement/service_level_agreement.py", line 634, in update_response_and_resolution_metrics
    set_response_by(doc, start_date_time, priority)
  File "apps/erpnext/erpnext/support/doctype/service_level_agreement/service_level_agreement.py", line 870, in set_response_by
    doc.response_by = get_expected_time_for(
  File "apps/erpnext/erpnext/support/doctype/service_level_agreement/service_level_agreement.py", line 656, in get_expected_time_for
    and get_time_in_timedelta(current_date_time.time()) > support_days[current_weekday].start_time
TypeError: '>' not supported between instances of 'datetime.timedelta' and 'datetime.time'

### Response Data

{
    "exception": "TypeError: '>' not supported between instances of 'datetime.timedelta' and 'datetime.time'",
    "exc_type": "TypeError",
    "_exc_source": "erpnext (app)",
    "exc": "[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 110, in application\\n    frappe.handler.handle()\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 49, in handle\\n    data = execute_cmd(cmd)\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 85, in execute_cmd\\n    return frappe.call(method, **frappe.form_dict)\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 1775, in call\\n    return fn(*args, **newargs)\\n  File \\\"apps/frappe/frappe/utils/typing_validations.py\\\", line 31, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"apps/frappe/frappe/rate_limiter.py\\\", line 154, in wrapper\\n    return fn(*args, **kwargs)\\n  File \\\"apps/payments/payments/overrides/payment_webform.py\\\", line 119, in accept\\n    doc.insert(ignore_permissions=True, ignore_mandatory=ignore_mandatory)\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 291, in insert\\n    self.run_before_save_methods()\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 1091, in run_before_save_methods\\n    self.run_method(\\\"validate\\\")\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 962, in run_method\\n    out = Document.hook(fn)(self, *args, **kwargs)\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 1322, in composer\\n    return composed(self, method, *args, **kwargs)\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 1306, in runner\\n    add_to_return_value(self, f(self, method, *args, **kwargs))\\n  File \\\"apps/erpnext/erpnext/support/doctype/service_level_agreement/service_level_agreement.py\\\", line 511, in apply\\n    process_sla(doc, sla)\\n  File \\\"apps/erpnext/erpnext/support/doctype/service_level_agreement/service_level_agreement.py\\\", line 530, in process_sla\\n    update_response_and_resolution_metrics(doc, sla.apply_sla_for_resolution)\\n  File \\\"apps/erpnext/erpnext/support/doctype/service_level_agreement/service_level_agreement.py\\\", line 634, in update_response_and_resolution_metrics\\n    set_response_by(doc, start_date_time, priority)\\n  File \\\"apps/erpnext/erpnext/support/doctype/service_level_agreement/service_level_agreement.py\\\", line 870, in set_response_by\\n    doc.response_by = get_expected_time_for(\\n  File \\\"apps/erpnext/erpnext/support/doctype/service_level_agreement/service_level_agreement.py\\\", line 656, in get_expected_time_for\\n    and get_time_in_timedelta(current_date_time.time()) > support_days[current_weekday].start_time\\nTypeError: '>' not supported between instances of 'datetime.timedelta' and 'datetime.time'\\n\"]"
}

### Module

support

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

manual install

**Comment by Amandeep8848** [comment]
PR : https://github.com/8848digital/erpnext/pull/197

**Comment by aasif-patel** [comment]
Resolved hence closing...
