### ISSUE TITLE
Unable to create Item Group 

### ISSUE THREAD

**Issue by pooja-pp8848** [8848digital/erpnext#200]
### Information about bug

![Screenshot 2024-10-08 175520](https://github.com/user-attachments/assets/495e565c-af1e-41a3-907a-18f4986e70e5)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by aasif-patel** [comment]
This occurs connection pooling testing i was doing...

**Comment by VishvParikh** [comment]
@pooja-pp8848  Error is not reflecting on server, can you please recheck. If solved then please Close this issue.

**Comment by pooja-pp8848** [comment]
Rechecked. Issue resolved. Closing the issue. @VishvParikh @aasif-patel
