### ISSUE TITLE
Item code unable to fetch in Material Request List although the item exists in item list 

### ISSUE THREAD

**Issue by pooja-pp8848** [8848digital/erpnext#204]
### Information about bug

![image](https://github.com/user-attachments/assets/6b9060ab-16d9-408e-97b2-b937a5757dc4)
![image](https://github.com/user-attachments/assets/d2c194f8-5f04-49ca-89b8-3510047fbc5a)
![image](https://github.com/user-attachments/assets/1eb7ad1a-528c-4b0e-8b25-a92dc0a7f224)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by VishvParikh** [comment]
@tinadn  issue is resolved please check it and close it

**Comment by tinadn** [comment]
Working Fine. Hence closing.
