### ISSUE TITLE
Stock Entry in the Connection tab getting error

### ISSUE THREAD

**Issue by vinod-8848digital** [8848digital/erpnext#208]
### Information about bug

**bug details**

- In the stock entry doctype, while clicking on the connection tab getting error in the console

![Screenshot from 2024-10-09 14-47-59](https://github.com/user-attachments/assets/17dc6483-6f03-4e69-9187-c94ffd9d77b3)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)
Frappe Framework: v15.41.0 (pre-prod)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Error in query:
column tabPurchase Order.stock_entry does not exist
LINE 3:    where "tabPurchase Order"."stock_entry" = 'MAT-STE-2024-0...
                 ^

5request.js:489 Error in query:
current transaction is aborted, commands ignored until end of transaction block

request.js:491
```

**Comment by VishvParikh** [comment]
@vinod-8848digital this is not issue 
it just print the console msg 
and if you think it is error then show me i will try to solved

**Comment by IamSaiyyamChhetri** [comment]
> @vinod-8848digital this is not issue it just print the console msg and if you think it is error then show me i will try to solved



![Screenshot 2024-10-10 at 5 18 48 PM](https://github.com/user-attachments/assets/1c796c5d-1b66-4c82-a2bd-aea536ad17e4)

No, Impact on count as @VishvParikh  updated it's just a console msg.

@aasif-patel, should we close this issue ?

**Comment by aasif-patel** [comment]
@tinadn please check and close it.

**Comment by tinadn** [comment]
Working fine. Hence closing.
