### ISSUE TITLE
Jinja Template Error while submitting Purchase Receipt - On click of "Submit" this error is displayed

### ISSUE THREAD

**Issue by pooja-pp8848** [8848digital/erpnext#216]
### Information about bug

![Screenshot 2024-10-10 at 1 27 13 PM](https://github.com/user-attachments/assets/01ac6c9e-b676-4632-a10e-9748292b4a62)

The PR gets submitted though. 

### Module

buying

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by IamSaiyyamChhetri** [comment]
From Notification.
html tag written inside curly braces.

Link to Notification : http://3.12.196.161/app/notification/Material%20Request%20Receipt%20Notification

![Screenshot 2024-10-10 at 1 43 27 PM](https://github.com/user-attachments/assets/7ff8b549-e0ab-47ab-9207-77552fc61208)

**Comment by tinadn** [comment]
Working fine. Hence Closing.
