### ISSUE TITLE
Jinja Template Error while cancelling Purchase Receipt 

### ISSUE THREAD

**Issue by pooja-pp8848** [8848digital/erpnext#217]
### Information about bug

![image](https://github.com/user-attachments/assets/d1752014-90af-45a1-8223-560b36e2f035)
The PR gets cancelled though

### Module

buying

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Working fine. Hence Closing.
