### ISSUE TITLE
Account head list not showing a drop-down when typing "OUTPUT" or "output".

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#221]
### Information about bug

Example - As we have configure Accounts head in system as Output In-State, so while writing OUTPUT or output drop-down list is not showing.
![image](https://github.com/user-attachments/assets/01a913a2-a3bf-49f5-9868-2bced39ce24d)
![image](https://github.com/user-attachments/assets/6286b313-f70d-4861-ba91-28f89c9cf8eb)
![image](https://github.com/user-attachments/assets/9142cde4-269f-4bc2-b8ad-e6f8efd5b109)

### Module

accounts

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Issue resolved. Hence Closing.
