### ISSUE TITLE
Payment Reconciliation Tool functionality is not working Properly- Even if we reconcile the purchase invoice with payment entry, Purchase invoice is still showing in payment reconciliation tool

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#224]
### Information about bug

Even if we reconcile the purchase invoice with payment entry, Purchase invoice is still showing in payment reconciliation tool and we can reconcile those paid invoices multiple times with payment entry which should not happen. 
![image](https://github.com/user-attachments/assets/b52bf13e-fc8c-4161-856a-e9ed21b14568)
![image](https://github.com/user-attachments/assets/7407dffd-5bd5-4d5a-a7b9-5582786aa60e)

### Module

accounts

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by vinod-8848digital** [comment]
@aasif-patel and @rushabhmaywade this issue aslo fixed

**Comment by vinod-8848digital** [comment]
@tinadn this issue also fixed

**Comment by tinadn** [comment]
Issue reolved. Hence closing.
