### ISSUE TITLE
After submission of Payment entry against sales invoice outstanding amount is showing in negative.

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#228]
### Information about bug

After submission of Payment entry against sales invoice outstanding amount should show 0 but its showing in negative 
![image](https://github.com/user-attachments/assets/cc5fdb29-1d81-41ad-adcf-fc3235300597)

### Module

accounts

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by vinod-8848digital** [comment]
@anandk-spyke-o1 and @aasif-patel  this issue is fixed in #258, its happening due to a common function

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
