### ISSUE TITLE
While Merging one item with another showing error

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#231]
### Information about bug

Rename any item with another existing item 
check the box of merge with existing item it will show error.
[image](https://github.com/user-attachments/assets/45a29b50-8ea1-4a21-8b4b-5f6abdbad8ee)
![image](https://github.com/user-attachments/assets/e9ce3573-0bb4-4d5b-abf4-120eeafbfc05)
![image](https://github.com/user-attachments/assets/e2046cb1-8725-4eb0-a4bb-6fa814e8c29b)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
This issue is similar to 
#230 
Hence Closing
