### ISSUE TITLE
While merging one account with another showing error 

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#233]
### Information about bug

![image](https://github.com/user-attachments/assets/bc041460-a89c-46ed-ac26-61e7d0c93ddc)

![image](https://github.com/user-attachments/assets/45868ed5-4f2a-400f-abfb-847aba012d08)

### Module

accounts

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Working fine. Hence closing.
