### ISSUE TITLE
Bug : The Depends On field is not mandatory when selecting Asset Owner in Asset Doctype. i.e. Company, Supplier or Customer

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/erpnext#244]
### Information about bug

The "Depends On" field is optional when selecting an Asset Owner in the Asset Doctype. This means that when you choose an owner, such as a supplier company or customer, you do not have to fill in the "Depends On" field to complete the asset submission process. This fields should be mandatory depends on

In below example when I choose customer as asset owner it shows me customer field but is is not mandatory to fill and it allow me to submit the asset entry

![image](https://github.com/user-attachments/assets/a712dccf-d7dc-4a96-bdd0-ea0a132faea9)

![image](https://github.com/user-attachments/assets/d150932e-c558-4e68-9744-fc0b53108184)

![image](https://github.com/user-attachments/assets/80852975-af99-48dc-8156-971d423f88c7)

![image](https://github.com/user-attachments/assets/5b06bc57-7390-468b-8ebf-69838e59f571)

### Module

assets

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by shubham-DT** [comment]
requirements id fullfield
PR 252

**Comment by tinadn** [comment]
Issue Resolved. Hence closing.
