### ISSUE TITLE
System Allows Duplicate Project Names with Different Capitalization

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#247]
### Information about bug

In the Project doctype, the system allows the creation of two projects with identical names if one is written in lowercase and the other in uppercase (e.g., "project" and "PROJECT"). This occurs even though the "Unique" field is checked, which is expected to prevent duplicate entries. The system does not recognize the names as duplicates due to the difference in capitalization.

![image](https://github.com/user-attachments/assets/f9675b70-7548-438c-9807-c2b060394297)

![image](https://github.com/user-attachments/assets/d0e7e961-e1a0-4512-add6-6944a564431e)

### Module

projects

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Resolved. Hence Closing.
