### ISSUE TITLE
System Fails to Trigger Pop-up Warning for Duplicate Project Names

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#248]
### Information about bug

![image](https://github.com/user-attachments/assets/a96568b5-fe7c-4677-a076-97832f807b3f)

When a project with the same name (regardless of case, whether in uppercase or lowercase) already exists, the system should display a pop-up warning that says, "Project name must be unique." However, this expected behavior is not triggered, and no pop-up appears.

### Module

projects

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Unable to get pop up "Project Name must be unique"
```

**Comment by tinadn** [comment]
Resolved. Hence Closing.
