### ISSUE TITLE
System allows duplicate project template name with different capitalization

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#249]
### Information about bug

![image](https://github.com/user-attachments/assets/e45b1530-2553-43e2-b0c1-143f2dbe66b0)

In the Project template doctype, the system allows the creation of two projects template with identical names if one is written in lowercase and the other in uppercase (e.g., "Handbag Manufacturing" and "HANDBAG MANUFACTURING"). The system does not recognize the names as duplicates due to the difference in capitalization.

### Module

projects

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Resolved. Hence Closing.
