### ISSUE TITLE
The Asset Category should accept only unique entries and be case-sensitive.

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/erpnext#253]
### Information about bug

In Asset Category doctype It does not allow the creation of duplicate entries; however, it permits the creation of asset category  if the case differs, such as uppercase, lowercase, or mixed capitalization, It should only allow unique entries in accordance with standardization.

For Example

I created Asset Category Equipment in Sentence case Uppercase and mixed capitalization.

![image](https://github.com/user-attachments/assets/effd0121-77c4-4ca2-9dac-ec5b46caf481)

![image](https://github.com/user-attachments/assets/74865268-343a-4d9b-bd95-366b0fa0c10e)

![image](https://github.com/user-attachments/assets/cd0eccfd-9214-4eb8-9f51-d9bdde45e824)

### Module

assets

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Findings on the issue:
Postgresql case-sensitive which means,
'Equipment', 'EQUIPMENT', 'eQUIPMENT', 'equipment' are treated as 4 different values
solution that may help:
Use citext Data Type
Create records using lowercase like (lower("project_name"));

**Comment by tinadn** [comment]
Resolved. Hence Closing.
