### ISSUE TITLE
The status filter in Asset Master should also include assets that are in draft which  are automatically created through a purchase receipt 

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/erpnext#262]
This status filter does not include assets which are created through purchase receipt and are in draft status 
![image](https://github.com/user-attachments/assets/ba033725-3d0c-44fd-a6ec-5f6f81c76a5c)

If the filter displayed below shows all assets that are in draft, regardless of how they were created.
![image](https://github.com/user-attachments/assets/c819eec1-92c3-4bf3-9723-488a57fba784)

Assets created through a purchase receipt do not display the status field in the Other Details section of the asset master until an "Available for Use" date is selected but the status is displayed as draft in list view
![image](https://github.com/user-attachments/assets/42530c53-7b6b-49d0-9280-a17ea41a3f60)

**Comment by shubham-DT** [comment]
Requirement fullfilled
PR 316
