### ISSUE TITLE
Item code filter should only display the item which are fixed asset in Asset Master

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/erpnext#274]
In the asset master, the item code filter currently shows all the items. It should display only items that are classified as fixed assets.
![image](https://github.com/user-attachments/assets/a2a7de35-5a2b-408a-8236-769ae8437ae6)

Example
It should have filter shown below
![image](https://github.com/user-attachments/assets/d7a1ca36-8c22-4b34-89b7-24fd0a056a10)

**Comment by vinod-8848digital** [comment]
@aasif-patel and @deepdoshi79 

the existing behaviour of  **list view of the asset** and **asset master data creation** is working same like mariadb site,

I tested in the mariadb local site, I am sharing the images ..

![Screenshot from 2024-10-15 17-39-26](https://github.com/user-attachments/assets/985fb245-ac18-4e7f-81eb-3a30162bc0b7)
![Screenshot from 2024-10-15 17-39-16](https://github.com/user-attachments/assets/17797807-57fa-4904-8c2e-3cd11dfe46bd)

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
