### ISSUE TITLE
In the Project Update doctype of the Project Module, the user selection dropdown only shows system users, and website users are not displayed in the dropdown.

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#280]
### Information about bug

In the Project Update doctype of the Project Module, only system users appear in the user selection dropdown. However, if the complete email address of a website user is manually entered, the system accepts it and allows submission. This issue is replicable on both the post gres instance and the demo site.
![image](https://github.com/user-attachments/assets/f75901e3-95e9-4ac6-8a10-532a91e1e9db)

### Module

projects

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by IamSaiyyamChhetri** [comment]
PR : https://github.com/8848digital/frappe-v15/pull/40

**Comment by tinadn** [comment]
Working fine. Hence closing.
