### ISSUE TITLE
Material Request: While exporting material request list in CSV or excel format getting an error Not Found

### ISSUE THREAD

**Issue by 8848swa** [8848digital/erpnext#29]
### Information about bug

While exporting material request list in CSV or excel format getting an error
![image](https://github.com/user-attachments/assets/4e73a2c7-d08a-4d12-b769-67113329d517)
![image](https://github.com/user-attachments/assets/da99d320-c148-482e-9426-e3ae05f787fb)

### Module

stock

### Version

ERPNext: v15.34.0 (version-15)

Frappe Framework: v15.41.0 (version-15)

Payments: v0.0.1 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Not Found
The resource you are looking for is not available
```

**Comment by bansodegaurav8848** [comment]
https://github.com/8848digital/frappe-v15/pull/10

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
