### ISSUE TITLE
The "Split Asset" function is throwing an error when accessed through the Manage Action button in Asset doctype

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/erpnext#304]
### Information about bug

When creating an asset and checking the existing asset checkbox, the asset quantity becomes enabled. If I enter a quantity of 4 and submit, then click on "Manage" and "Split Asset," I received the following error:

![image](https://github.com/user-attachments/assets/d03029fb-42fe-45cf-b275-5e716f02bc53)
![image](https://github.com/user-attachments/assets/b2af2070-e258-4bc3-adfb-83e447dca329)
![image](https://github.com/user-attachments/assets/9c967f22-83b7-4133-af24-cf83f0fdf2ac)
It displays the above error when the depreciation method is specified in the asset category. 
![image](https://github.com/user-attachments/assets/ad112af7-898a-4925-a685-41f2f22adc04)
If the depreciation method is not selected in the asset category, the system allows the asset to be split.

### Module

assets

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Asset/ACC-ASS-2024-00033
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/assets/doctype/asset/asset.py", line 1042, in split_asset
    new_asset = create_new_asset_after_split(asset, split_qty)
  File "apps/erpnext/erpnext/assets/doctype/asset/asset.py", line 1165, in create_new_asset_after_split
    for term in depr_schedule:
TypeError: 'NoneType' object is not iterable

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"asset_name": "ACC-ASS-2024-00033",
		"split_qty": 2
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.assets.doctype.asset.asset.split_asset",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "TypeError: 'NoneType' object is not iterable",
	"exc_type": "TypeError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by tinadn** [comment]
Issue reolved. Hence closing.
