### ISSUE TITLE
In the Project doctype, I can see and select sales orders from different companies, which should not be the case. Similarly, in the Sales Order doctype, when I select a specific company, I should only see projects associated with that company. However, the dropdown displays all projects, including those associated with other companies. This issue is also present on the demo site.

### ISSUE THREAD

**Issue by yatishdarji** [8848digital/erpnext#309]
### Discussed in https://github.com/8848digital/erpnext/discussions/307

<div type='discussions-op-text'>

<sup>Originally posted by **Purvi8848** October 16, 2024</sup>
In the Project doctype, I can see and select sales orders from different companies, which should not be the case. Similarly, in the Sales Order doctype, when I select a specific company, I should only see projects associated with that company. However, the dropdown displays all projects, including those associated with other companies. This issue is also present on the demo site.

![image](https://github.com/user-attachments/assets/0d804846-dc8c-410a-9dfd-d502191c9758)

![image](https://github.com/user-attachments/assets/3ed73ae9-8a98-4742-bbc8-7aeb75f6e6ac)

</div>

**Comment by aasif-patel** [comment]
@IamSaiyyamChhetri you can raise PR to standar ERPNext too for this.

**Comment by tinadn** [comment]
@IamSaiyyamChhetri On project doctype its working fine
Please check for sales order
![image](https://github.com/user-attachments/assets/7590de63-092a-4dde-af8d-3ebe0cf20a18)

**Comment by tinadn** [comment]
Issue Resolved. Hence closing.

**Comment by IamChhteri** [comment]
> @IamSaiyyamChhetri you can raise PR to standar ERPNext too for this.

Yes. testing is complete and it's working.
