### ISSUE TITLE
POS item available quantity is not matching with balance quantity in stock ledger report. 

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#314]
### Information about bug

![image](https://github.com/user-attachments/assets/eda847a1-3a1b-4b10-b4dd-8ced3639904e)
![image](https://github.com/user-attachments/assets/b4ed9da4-104e-4f6c-ba74-420130ead382)

### Module

accounts, selling

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by IamSaiyyamChhetri** [comment]
Hi @rushabhmaywade,
This issue is due to "Do reposting for each Stock Transaction" checkbox was checked.
SLE was getting creating but the Bin dt actual_qty was not getting updated.

For now it's uncheck and showing correct qty in POS.

**Comment by rushabhmaywade** [comment]
@aasif-patel  @IamSaiyyamChhetri, Tested, Working Properly

**Comment by aasif-patel** [comment]
Resolved hence closing..
