### ISSUE TITLE
Sales invoice status is showing in submitted or draft status but it should show its actual status. 

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#333]
### Information about bug

Actual status means the list attached below
![image](https://github.com/user-attachments/assets/0c7adacf-fb4a-4155-b398-bf1a7295f6a5)
![image](https://github.com/user-attachments/assets/aace9f94-5102-405c-8cde-086c85a4f4ee)

### Module

accounts

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by Abhishek8848** [comment]
Issue has been resolved.
Attached Screenshot.
![Screenshot 2024-10-22 130431](https://github.com/user-attachments/assets/aa35cc3e-e334-455c-ab89-a5dc02aeb301)
