### ISSUE TITLE
The custodian (employee) should be filtered based on the selected company in the asset doctype.

### ISSUE THREAD

**Issue by yatishdarji** [8848digital/erpnext#334]
### Discussed in https://github.com/8848digital/erpnext/discussions/330

<div type='discussions-op-text'>

<sup>Originally posted by **deepdoshi79** October 18, 2024</sup>
When selecting a custodian (employee) in the asset, no company filter is applied. It shows values of all the companies
![image](https://github.com/user-attachments/assets/9546fe84-f833-4b64-9174-519ee532eddf)
Reference field
![image](https://github.com/user-attachments/assets/b92fd732-e457-46bc-a529-96f4286e03e3)
</div>

**Comment by hrishikesh8848** [comment]
Working fine, you can close this

**Comment by aasif-patel** [comment]
Tested by @hrishikesh8848 hence closing.
