### ISSUE TITLE
When an employee creates a timesheet, the related customer should automatically be fetched from the project.This functionality is not working. I'm facing same issue on the demo site as well.

### ISSUE THREAD

**Issue by yatishdarji** [8848digital/erpnext#335]
### Discussed in https://github.com/8848digital/erpnext/discussions/322

<div type='discussions-op-text'>

<sup>Originally posted by **Purvi8848** October 17, 2024</sup>
When an employee creates a timesheet, the related customer should automatically be fetched from the project.This functionality is not working. I am facing same issue on the demo site as well.

![image](https://github.com/user-attachments/assets/abb3f9c7-5c42-4107-a80a-6505c8c38f97)

Customer is mapped in project

![image](https://github.com/user-attachments/assets/cf76e069-8461-4843-92cc-2e9f9a0d3eeb)

</div>

**Comment by Purvi8848** [comment]
Fetching company and customer details directly from the project is not required. Instead, a company filter needs to be applied to the project field to enable more efficient selection. A discussion has been raised for it.
