### ISSUE TITLE
In the Asset Depreciation Ledger, assets, asset categories, and cost centers should be filtered based on the selected company.

### ISSUE THREAD

**Issue by yatishdarji** [8848digital/erpnext#336]
### Discussed in https://github.com/8848digital/erpnext/discussions/319

<div type='discussions-op-text'>

<sup>Originally posted by **deepdoshi79** October 17, 2024</sup>
In the Asset Depreciation Ledger, assets, asset categories, and cost centers should be filtered based on the selected company. It shows values of all the companies
![image](https://github.com/user-attachments/assets/71346965-adf8-40b2-acca-9f4ca25fd0c4)
Reference Ledger
![image](https://github.com/user-attachments/assets/5356ac9e-07f4-40fe-a184-c050f552b6b2)

</div>

**Comment by deepdoshi79** [comment]
Similar Feature Required in Fixed Asset Register and Asset Depreciations and Balances Reports

**Comment by manoj8848** [comment]
Completed and deployed on asset module.
https://github.com/8848digital/Assets/pull/30

**Comment by yatishdarji** [comment]
@deepdoshi79 Test it and inform if it's working fine now

**Comment by deepdoshi79** [comment]
Enhancement Done. Functionality Working.
