### ISSUE TITLE
Purchase Receipt Selection in Assets Not Company-Filtered

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/erpnext#338]
### Information about bug

In the asset, when manually selecting a purchase receipt, it should be filtered based on the selected company. Currently, it does not filter, and selecting a purchase receipt from a different company changes the company automatically.
![image](https://github.com/user-attachments/assets/f34d059f-31cc-4c65-9df7-e534aa0ff9bf)

Example:
When an asset is created for PP Ltd and a purchase receipt from 8848 Digital is selected, it changes the asset's company to 8848 Digital.
![image](https://github.com/user-attachments/assets/eee1e4d8-50e0-4901-8730-dab908338e61)
![image](https://github.com/user-attachments/assets/c79c48da-8b80-46cd-b5fb-8480c0105a90)
![image](https://github.com/user-attachments/assets/3f3cb261-3a5c-4ded-8247-38b6782da4e3)

### Module

assets

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by deepdoshi79** [comment]
issue is still occurring

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
