### ISSUE TITLE
In the project template section, there’s a filter for "is template." It should only allow tasks marked as templates, but the system still lets us add tasks that aren’t marked as template.

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#340]
### Information about bug

In the project template section, there’s a filter for "is template." It should only allow tasks marked as templates, but the system still lets us add tasks that aren’t marked as template.

![image](https://github.com/user-attachments/assets/e2420c54-4e01-419e-af34-3c4264481d0c)

![image](https://github.com/user-attachments/assets/ab2589a1-c921-4315-8820-9bb58069c33c)

For TASK-2024-00017, even though the "Is Template" checkbox is unchecked, the system still allows the task to be added and saved under the Project Template doctype.

![image](https://github.com/user-attachments/assets/9c42ab41-207b-41f0-af1c-79ede01a6073)

### Module

projects

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by aasif-patel** [comment]
Resolved hence closing.
