### ISSUE TITLE
All mandatory fields do not get checked once 'Select Mandatory' is clicked in Data Import Doctype

### ISSUE THREAD

**Issue by pooja-pp8848** [8848digital/erpnext#345]
### Information about bug

Data import doctype > Download template > 'Select Mandatory'

![image](https://github.com/user-attachments/assets/00f81837-627d-4631-833d-7c12de564239)

![image](https://github.com/user-attachments/assets/2944526c-d357-4c70-9424-4aee9789349f)

### Module

other

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by anandk-spyke-o1** [comment]
On click of Select Mandatory button will select mandatory fields of Parent Doctype and the mandatory fields of those child tables which is of type mandatory. But it wont select the mandatory fields of those child tables which aren't of type mandatory.
[ code reference]
let mandatory_table_fields = frappe.meta
			.get_table_fields(this.doctype)
			.filter((df) => df.reqd)
			.map((df) => df.fieldname);
[ Solution ]
if we remove '.filter((df) => df.reqd)' from the code then it is working fine, but needs to be discussed before pushing on the scale of necessity and impact.

**Comment by aasif-patel** [comment]
@pooja-pp8848 we can consider this as Enhancement.

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
