### ISSUE TITLE
Filter Purchase invoices with the "update stock" option enabled in Asset

### ISSUE THREAD

**Issue by yatishdarji** [8848digital/erpnext#346]
### Discussed in https://github.com/8848digital/erpnext/discussions/343

<div type='discussions-op-text'>

<sup>Originally posted by **deepdoshi79** October 21, 2024</sup>
When selecting a purchase invoice for an asset, only invoices with the "update stock" option enabled should be displayed, rather than showing a message during submission.
![image](https://github.com/user-attachments/assets/5323d78d-29b0-48f1-b89d-38f144521285)
![image](https://github.com/user-attachments/assets/44c74abe-be0b-4123-ac0b-3e8db8e16d0a)
![image](https://github.com/user-attachments/assets/11a02983-4a5b-487e-8860-cc781146d355)
</div>

**Comment by anandk-spyke-o1** [comment]
Raised PR on Asset app repo https://github.com/8848digital/Assets/pull/24

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
