### ISSUE TITLE
The task status is not updating to "Overdue," even though the task remains open past the expected completion date. Despite being edited 5 days ago, the status is still marked as "Open" instead of changing to "Overdue."

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#347]
### Information about bug

The task status is not updating to "Overdue," even though the task remains open past the expected completion date. Despite being edited 5 days ago, the status is still marked as "Open" instead of changing to "Overdue."

![image](https://github.com/user-attachments/assets/1013f65b-50b3-4493-bd73-1ff7f42c9597)

### Module

projects

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by anandk-spyke-o1** [comment]
Task status change depends on a daily scheduler :- erpnext.projects.doctype.task.task.set_tasks_as_overdue

The scheduler is inactive on UAT instance 
![inactive_scheduler](https://github.com/user-attachments/assets/7bf40cbe-3025-42d1-9226-a9150d0460c0)

Then if the "Expected End Date" is before the current date and then the scheduler will change it's status to "Overdue".

I've tested in local working fine, enable scheduler on UAT and test there also it should work

**Comment by aasif-patel** [comment]
@tinadn enable the scheduler and close this issue after testing.

**Comment by tinadn** [comment]
@aasif-patel as task status is set to completed, it will not change to overdue now as mentioned in query. Schedulers are enabled now. 
@Purvi8848 test this issue again with new task.

**Comment by tinadn** [comment]
Working fine. Hence closing.
