### ISSUE TITLE
Data Import - Asset Import - System producing error although required data is present in the import template. 

### ISSUE THREAD

**Issue by pooja-pp8848** [8848digital/erpnext#351]
### Information about bug

![image](https://github.com/user-attachments/assets/e44348cf-912e-4f9b-8feb-0d853a9740b8)
![image](https://github.com/user-attachments/assets/c6ebf00d-75f0-409f-b432-dec6d617d255)
![image](https://github.com/user-attachments/assets/06030806-6943-43e9-8c27-9f27b8b33471)

Same template got successfully imported on my personal instance- 

![image](https://github.com/user-attachments/assets/379d9f0f-af59-44ce-87e3-0b368cf3ec91)

### Module

other

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Working fine. Hence closing.
