### ISSUE TITLE
Purchase Invoice Selection in Assets Not Company-Filtered

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/erpnext#366]
### Information about bug

In the asset, when manually selecting a purchase invoice, it should be filtered based on the selected company. Currently, it does not filter, and selecting a purchase invoice from a different company changes the company automatically.
![image](https://github.com/user-attachments/assets/f43b2181-826a-4735-a620-d03346dd1993)
Example:
When an asset is created for PP Ltd and a purchase invoice from 8848 Digital is selected, it changes the asset's company to 8848 Digital.
![image](https://github.com/user-attachments/assets/1c195e6e-9824-4bff-b9d5-069ecf4cf133)
![image](https://github.com/user-attachments/assets/9819b12b-b927-4df8-ba58-3c3837cc4506)
![image](https://github.com/user-attachments/assets/886a59f2-062d-4aec-8e03-c0463cb0e84c)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by aasif-patel** [comment]
@deepdoshi79 please raise this in Assets app.
