### ISSUE TITLE
The Auto Material Request is not being generated in the system and the Scheduled Log shows the task reorder_item.reorder_item with a failed status.

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#374]
### Information about bug

![image](https://github.com/user-attachments/assets/82496132-347c-4ddf-b09a-dfc32130d0be)

### Module

stock

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

### Installation method

None

**Comment by shubham-DT** [comment]
Issue Resolved

**Comment by tinadn** [comment]
Issue Resolved. Hence closing.
