### ISSUE TITLE
In the Timesheet Doctype, when using the timer, the system should automatically fetch the project and show only the tasks related to that project in the dropdown menu.

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#380]
### Information about bug

In the Timesheet Doctype, when using the timer, the system should automatically fetch the project and show only the tasks related to that project in the dropdown menu.

![image](https://github.com/user-attachments/assets/6c6f4088-3807-48f2-ba21-724958e7d0bf)

![image](https://github.com/user-attachments/assets/a9990173-b707-4d8b-8bea-a990ad675c0d)

### Module

projects

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by yatishdarji** [comment]
Not Required, hence closing
