### ISSUE TITLE
In Report View, the system should dynamically adjust the available filter options. Specifically, when a particular company is selected in the filter, only the relevant dropdown menus and options associated with that company should be displayed in other filters.

### ISSUE THREAD

**Issue by yatishdarji** [8848digital/erpnext#432]
### Discussed in https://github.com/8848digital/erpnext/discussions/421

<div type='discussions-op-text'>

<sup>Originally posted by **rushabhmaywade** October 24, 2024</sup>
![image](https://github.com/user-attachments/assets/9b844cf5-e93f-4b3e-b142-eaea800acb26)
</div>

**Comment by chintanshah8848** [comment]
PR raised Already for Product Bundle and Item Shortage Report:
https://github.com/8848digital/erpnext/pull/433
https://github.com/8848digital/erpnext/pull/428

**Comment by tinadn** [comment]
Issue Resolved. Hence closing.

**Comment by shyam-kumar8848** [comment]
Dear User,Thank you for contacting 8848 Support.We would like to confirm that we
have received your request for Re: [8848digital/erpnext] In Report View, the
system should   dynamically adjust the available filter options. Specifically,
when a   partic, and the request ID assigned to your case is EV00007.Our team is
currently reviewing your request and will provide a detailed response shortly.If
you require immediate assistance or have further queries, do not hesitate to
contact us.




|  | 
Thanks and Regards
SUPPORT TEAM


---




 +91 9004508848
 



***@***.******@***.***)




[8848digital.com](http://8848digital.com)

 |



Leave this conversation: http://pms.com:8000/api/method/frappe.email.queue.unsubscribe?email=reply%2Ba3bqw3lfep747t72frxyvyofmqtlrevbnhhjxqj6cy%40reply.github.com&doctype=Event&name=EV00007&_signature=9f374d223689b8e553baa5aea60577307bdc3c81e43e30afd71baf336121c7d9c8c296194cd3f32cd4c30b7dab710f96c665a13410886aab8d1217be4576c927

**Comment by shyam-kumar8848** [comment]
Dear User,Thank you for contacting 8848 Support.We would like to confirm that we
have received your request for Re: [8848digital/erpnext] In Report View, the
system should   dynamically adjust the available filter options. Specifically,
when a   partic, and the request ID assigned to your case is EV00008.Our team is
currently reviewing your request and will provide a detailed response shortly.If
you require immediate assistance or have further queries, do not hesitate to
contact us.




|  | 
Thanks and Regards
SUPPORT TEAM


---




 +91 9004508848
 



***@***.******@***.***)




[8848digital.com](http://8848digital.com)

 |



Leave this conversation: http://pms.com:8000/api/method/frappe.email.queue.unsubscribe?email=reply%2Ba3bqw3lo2ye3upvud4s7luofmqtltevbnhhjxqj6cy%40reply.github.com&doctype=Event&name=EV00008&_signature=a8a5aacecf3fc13b440c7c273519c234560e775e2d75453a9f16315973294cd0d45ebc78880c771fc6f33f8e2ef36c296e6e19a819f7dde1db21be63c6870826
