### ISSUE TITLE
Payment Terms

### ISSUE THREAD

**Issue by yatishdarji** [8848digital/erpnext#446]
### Discussed in https://github.com/8848digital/erpnext/discussions/445

<div type='discussions-op-text'>

<sup>Originally posted by **Ankur8848** October 25, 2024</sup>
We intend to simplify payment terms so as to comply with modern and applicable business requirements the detailed document of which is attached as follows:

https://docs.google.com/document/d/1A-BLpYGq_WS3WxcNRqn1e7IXPXdozcEe/edit </div>

**Comment by IamSaiyyamChhetri** [comment]
Issue : #644

**Comment by IamSaiyyamChhetri** [comment]
Removing all development as per discussion.
#644
