### ISSUE TITLE
The Work Order Stock Report is not generating data accurately based on the applied warehouse filter.

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#447]
### Information about bug

![image](https://github.com/user-attachments/assets/c9ab20b7-9209-4590-9824-5b8f6046a72f)

### Module

manufacturing

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by bansodegaurav8848** [comment]
https://github.com/8848digital/erpnext/pull/449

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
