### ISSUE TITLE
Feature for Payment Reconciliation doctype

### ISSUE THREAD

**Issue by vinod-8848digital** [8848digital/erpnext#450]
### Feature for Payment Reconciliation doctype

As we know Payment Reconciliation is single and virtual doctype

● It will not store any records in the database
● But user want to know, how many transactions are made by using payment reconciliation
● For that, Need to Create two doctypes

**Payment Reconciliation Records (parent doctype) User can’t Create**
    ◆ Following fields to add in the parent doctype
        ● Company link to Company doctype
        ● Party Type link to Doctype
        ● Party Dynamic Link to Party Type
        ● Receivable / Payable Account Link to Account
        ● Default Advance Account Link to Account
        ● Allocation Table to Payment Reconciliation Allocation Records

**Payment Reconciliation Allocation Records (child doctype)**
    ◆ It is a replica of Payment Reconciliation Allocation doctype that exists in the Accounts module.
        ● Once the reconcile button is clicked on the payment reconciliation doctype, then Create the Payment Reconciliation 
           Records.
        ● Payment Reconciliation Records will store the all the transactions are made through the payment reconciliation
        ● It is a submittable doctype, user not able to create it, not able to cancel and delete it.
        ● All the Parent doctype fields should get fetch from Payment reconciliation doctype.
        ● All the child table doctype fields should get fetch from the Payment Reconciliation Allocation

**Comment by aasif-patel** [comment]
Tested working fine, Hence closing...
