### ISSUE TITLE
The system currently allows the selection of a parent warehouse when creating a sales order, which should not be permitted.

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#453]
### Information about bug

![image](https://github.com/user-attachments/assets/3bdcf8de-b75d-4613-b973-68a8b11b0b66)

### Module

stock, selling

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by IamSaiyyamChhetri** [comment]
This is the common issue which can be solved through : #448

**Comment by shubham-DT** [comment]
Noted

**Comment by aasif-patel** [comment]
@IamSaiyyamChhetri please check this issue not resolved connect with @rushabhmaywade if needed.

**Comment by shubham-DT** [comment]
@rushabhmaywade can you please confirm whether this issue is fixed or not?

**Comment by rushabhmaywade** [comment]
@shubham-DT Not resolved  Its still showing the parent warehouse.

**Comment by shubham-DT** [comment]
Resolved

**Comment by tinadn** [comment]
Issue Resolved. Hence closing.
