### ISSUE TITLE
Timesheet doctype do not have "create sales button" 

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#458]
### Information about bug

Timesheet doctype do not have "create sales button" after submitting timesheet, there should be button for "Create Sales Invoice"

![image](https://github.com/user-attachments/assets/230af42e-e44d-480b-b3a6-4140bf240f4b)

### Module

projects

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by Abhishek8848** [comment]
It working fine.

If following condition satisfying then "Create Sales Invoice" button will show-
1. Amount Billied < 100 
2. if "total_billable_hours" available 
3. total_billable_hours > total_billed_hours
				
				
http://3.12.196.161/app/timesheet/TS-2024-00038

![image](https://github.com/user-attachments/assets/0ae19b55-62ba-4798-b1ce-af6c6160e52f)

**Comment by tinadn** [comment]
Working Fine.
