### ISSUE TITLE
The system is displaying a message to link accounts, even though it is not mandatory in the Company Master.

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#466]
### Information about bug

![image](https://github.com/user-attachments/assets/a2044ae5-2f88-48ca-b10d-8334d2d24804)

### Module

accounts

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by IamSaiyyamChhetri** [comment]
@tinadn, this issue is resolved can you please close this ticket.
I've confirmed with @rushabhmaywade

**Comment by tinadn** [comment]
Working fine. Hence closing.
