### ISSUE TITLE
AssertionError: 1730160000.0 is not an instance of <class 'int'>

### ISSUE THREAD

**Issue by hrishikesh8848** [8848digital/erpnext#494]
### Information about bug

![image](https://github.com/user-attachments/assets/1a2c40b0-ea7d-4df1-86dd-e8d961a4790a)

### Module

stock

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/item/test_item.py", line 635, in test_heatmap_data
    self.assertIsInstance(timestamp, int)
AssertionError: 1730160000.0 is not an instance of <class 'int'>
```

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
