### ISSUE TITLE
AssertionError: None != '_Test Account Excise Duty @ 12 - _TC'

### ISSUE THREAD

**Issue by hrishikesh8848** [8848digital/erpnext#496]
### Information about bug

![image](https://github.com/user-attachments/assets/99720ab0-1816-4e5a-b308-fc0273387218)

### Module

stock

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/item/test_item.py", line 255, in test_item_tax_template
    self.assertEqual(details.item_tax_template, data["item_tax_template"])
AssertionError: None != '_Test Account Excise Duty @ 12 - _TC'
```

**Comment by tinadn** [comment]
Resolved. Hence Closing.
