### ISSUE TITLE
Purchase Receipt Test Case: test_valuation_taxes_lcv_repost_after_billing

### ISSUE THREAD

**Issue by chintanshah8848** [8848digital/erpnext#526]
### Information about bug

FAIL: test_valuation_taxes_lcv_repost_after_billing (erpnext.stock.doctype.purchase_receipt.test_purchase_receipt.TestPurchaseReceipt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/purchase_receipt/test_purchase_receipt.py", line 2972, in test_valuation_taxes_lcv_repost_after_billing
    self.assertSequenceEqual(expected_gle, gl_entries)
AssertionError: Sequences differ: (('Stock Received But Not Billed - _TC', [230 chars]TC')) != [('_Test Rejected Warehouse Return Qty Wa[246 chars]TC')]

First differing element 0:
('Stock Received But Not Billed - _TC', 0, [15 chars]_TC')
('_Test Rejected Warehouse Return Qty Wareh[35 chars]_TC')

- (('Stock Received But Not Billed - _TC', 0, 10000, 'Main - _TC'),
-  ('Freight and Forwarding Charges - _TC', 0, 2000, 'Main - _TC'),
-  ('Expenses Included In Valuation - _TC', 0, 2000, 'Main - _TC'),
-  ('_Test Rejected Warehouse Return Qty Warehouse - _TC',
? ^

+ [('_Test Rejected Warehouse Return Qty Warehouse - _TC',
? ^

-   14000,
+   14000.0,
?        ++

-   0,
+   0.0,
?   ++

-   'Main - _TC'))
?                ^

+   'Main - _TC'),
?                ^

+  ('Stock Received But Not Billed - _TC', 0.0, 10000.0, 'Main - _TC'),
+  ('Freight and Forwarding Charges - _TC', 0.0, 2000.0, 'Main - _TC'),
+  ('Expenses Included In Valuation - _TC', 0.0, 2000.0, 'Main - _TC')]

### Module

stock

### Version

Frappe - v15
Erpnext - v15

### Installation method

None

**Comment by chintanshah8848** [comment]
https://github.com/8848digital/erpnext/pull/528

**Comment by tinadn** [comment]
Issue resolved. Hence Closing.
