### ISSUE TITLE
Not able to view Lead Details Report- Showing error as DocType user not found

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#53]
### Information about bug

![image](https://github.com/user-attachments/assets/00e3759c-4662-4efd-a7e5-bee8e41af03a)

### Module

CRM

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by aasif-patel** [comment]
PR https://github.com/8848digital/erpnext/pull/101

**Comment by aasif-patel** [comment]
Resolved hence closing
