### ISSUE TITLE
Test Case for Purchsase Receipt: test_purchase_return_partial 

### ISSUE THREAD

**Issue by chintanshah8848** [8848digital/erpnext#532]
### Information about bug

======================================================================
FAIL: test_purchase_return_partial (erpnext.stock.doctype.purchase_receipt.test_purchase_receipt.TestPurchaseReceipt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/purchase_receipt/test_purchase_receipt.py", line 462, in test_purchase_return_partial
    self.assertEqual(pr.per_billed, 100)
AssertionError: 60.0 != 100

----------------------------------------------------------------------
Ran 1 test in 5.521s

FAILED (failures=1)

### Module

stock

### Version

Frappe - v15
Erpnext - 15

### Installation method

None

**Comment by chintanshah8848** [comment]
https://github.com/8848digital/erpnext/pull/534

**Comment by tinadn** [comment]
Issue resolved. Hence Closing.
