### ISSUE TITLE
Purchase Receipt Test Case Failure test_stock_transfer_from_purchase_receipt_with_valuation 

### ISSUE THREAD

**Issue by chintanshah8848** [8848digital/erpnext#535]
### Information about bug

FAIL: test_stock_transfer_from_purchase_receipt_with_valuation (erpnext.stock.doctype.purchase_receipt.test_purchase_receipt.TestPurchaseReceipt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/purchase_receipt/test_purchase_receipt.py", line 1062, in test_stock_transfer_from_purchase_receipt_with_valuation
    self.assertEqual(gle.account, expected_gle[i][0])
AssertionError: '_Test Account Stock In Hand - TCP1' != 'Stock In Hand - TCP1'
- _Test Account Stock In Hand - TCP1
? --------------
+ Stock In Hand - TCP1

### Module

stock

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

sales_commission: v0.0.1 (master)

### Installation method

None

**Comment by tinadn** [comment]
Resolved. Hence closing.
