### ISSUE TITLE
Purchase Invoice Test Case: test_gain_loss_with_advance_entry

### ISSUE THREAD

**Issue by chintanshah8848** [8848digital/erpnext#536]
### Information about bug

Traceback (most recent call last):
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/test_purchase_invoice.py", line 1413, in test_gain_loss_with_advance_entry
    self.assertEqual(expected_gle[i][0], gle.account)
AssertionError: '_Test Payable USD - _TC' != 'Cash - _TC'
- _Test Payable USD - _TC
+ Cash - _TC

----------------------------------------------------------------------
Ran 1 test in 1.461s

FAILED (failures=1)

### Module

accounts

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

sales_commission: v0.0.1 (master)

### Installation method

None

**Comment by chintanshah8848** [comment]
https://github.com/8848digital/erpnext/pull/537

**Comment by tinadn** [comment]
Issue resolved. Hence Closing.
