### ISSUE TITLE
Purchase Invoice Test Case Issue: test_gl_entries_without_perpetual_inventory

### ISSUE THREAD

**Issue by chintanshah8848** [8848digital/erpnext#547]
### Information about bug

FAIL: test_gl_entries_without_perpetual_inventory (erpnext.accounts.doctype.purchase_invoice.test_purchase_invoice.TestPurchaseInvoice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chintan/postgres-testing/frappe-bench-postgres/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/test_purchase_invoice.py", line 132, in test_gl_entries_without_perpetual_inventory
    self.assertEqual([d.debit, d.credit], expected_gl_entries.get(d.account))
AssertionError: Lists differ: [0.0, 1512.3] != [0, 1512.0]

First differing element 1:
1512.3
1512.0

- [0.0, 1512.3]
?   --       ^

+ [0, 1512.0]
?          ^

----------------------------------------------------------------------
Ran 1 test in 0.890s

FAILED (failures=1)

### Module

accounts

### Version

Assets: v0.0.1 (pre-prod)
ERPNext: v15.34.0 (pi_test_cases_issues)
Frappe Framework: v15.41.0 (pre-prod)
Payments: v0.0.1 (version-15)
sales_commission: v0.0.1 (master)

### Installation method

None

**Comment by chintanshah8848** [comment]
https://github.com/8848digital/erpnext/pull/542

**Comment by tinadn** [comment]
Resolved. Hence Closing.
