### ISSUE TITLE
When creating a Landed Cost Voucher and linking it to a Purchase Invoice, the LCV should ideally appear in the Connections tab of the Purchase Invoice doctype.

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#554]
### Information about bug

![image](https://github.com/user-attachments/assets/fb792ae1-dbd1-4d92-a0d7-a84765c2bbdd)
![image](https://github.com/user-attachments/assets/e9526462-1eed-4e66-b6f8-844569310982)

### Module

accounts, stock

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

### Installation method

None

**Comment by tinadn** [comment]
Resolved. Hence closing.
