### ISSUE TITLE
Not able to select doctype in Customize form and Custom Field doctypes

### ISSUE THREAD

**Issue by vinod-8848digital** [8848digital/erpnext#558]
### Information about bug

go to the customize form or custom field doctype

select form type in customize form for (CUSTOMIZE FORM)
All the doctypes are coming in dropdown but when we select any one in that, the field is getting empty

select form type in doctype field for (CUSTOM FIELD)
All the doctypes are coming in dropdown but when we select any one in that, the field is getting empty

https://github.com/user-attachments/assets/52cb6248-6cf5-4663-805d-a55e8da08cd3

### Module

other

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

sales_commission: v0.0.1 (master)

### Installation method

None

**Comment by tinadn** [comment]
Issue Resolved. Hence closing.
