### ISSUE TITLE
Every time when we select "Transporter" system gives error message in driver doctype.

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#564]
### Information about bug

Every time when we select "Transporter" system gives error message in driver doctype. 
![image](https://github.com/user-attachments/assets/4a61e9c5-81b9-41a0-b509-fddd1fa4c374)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Resolved. Hence closing.
