### ISSUE TITLE
FAIL: test_stock_reco_with_legacy_batch (erpnext.stock.doctype.stock_reconciliation.test_stock_reconciliation.TestStockReconciliation)

### ISSUE THREAD

**Issue by hrishikesh8848** [8848digital/erpnext#579]
### Information about bug

FAIL: test_stock_reco_with_legacy_batch (erpnext.stock.doctype.stock_reconciliation.test_stock_reconciliation.TestStockReconciliation)

### Module

stock

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pi_test_cases_issues)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

sales_commission: v0.0.1 (master)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
  File "/home/hrishikesh/8848digital/postgres/frappe-bench-postgres/apps/erpnext/erpnext/stock/doctype/stock_reconciliation/test_stock_reconciliation.py", line 1272, in test_stock_reco_with_legacy_batch
    self.assertEqual(sr.items[0].current_qty, 20)
AssertionError: 0.0 != 20
```

**Comment by anandk-spyke-o1** [comment]
Working fine now.
![Screenshot from 2024-11-06 21-49-07](https://github.com/user-attachments/assets/7c07e28a-9f48-4c3e-8572-e0041f88c8fa)

**Comment by tinadn** [comment]
Working fine. Hence closing.
