### ISSUE TITLE
Project field value getting empty while saving - Process Statement Of Accounts

### ISSUE THREAD

**Issue by vinod-8848digital** [8848digital/erpnext#598]
### Information about bug

Go to the Process Statement Of Accounts
fill the details and select the projects
save the document, then project field value will get empty

https://github.com/user-attachments/assets/6c4399e4-c256-4f11-9939-e8194874000a

### Module

accounts

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

sales_commission: v0.0.1 (master)

### Installation method

None

**Comment by vinod-8848digital** [comment]
@Abhishek8848  the same issue exist in standard mariadb site also

**Comment by tinadn** [comment]
Resolved. Hence closing.
