### ISSUE TITLE
When a subcontracting order is prepared following the submission of a Purchase Order, it does not get reflected in the Connections section.

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#599]
### Information about bug

When a subcontracting order is prepared following the submission of a Purchase Order, it does not get reflected in the Connections section.

![image](https://github.com/user-attachments/assets/364b4a3e-296a-4732-b1c6-bcfb2b423ba3)

### Module

stock

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by shubham-DT** [comment]
linked with #554

**Comment by tinadn** [comment]
Working fine. Hence closing.
