### ISSUE TITLE
Sales Invoice Cost Center Error. This error is the same as in Sales Order, Purchase Invoice, and Purchase Order.

### ISSUE THREAD

**Issue by shyamrathod12** [8848digital/erpnext#6]
### Information about bug

In sales invoice Selecting the Cost Center throwing an error
![Screenshot from 2024-09-04 12-34-20](https://github.com/user-attachments/assets/230af7b5-b3c9-4ad2-9d95-d5c25e1ef58a)
 

### Module

accounts

### Version

ERPNext: v15.34.0 (version-15)

Frappe Framework: v15.40.0 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.40.0"
}
```
### Route
```
Form/Sales Invoice/new-sales-invoice-zekkilqscs
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 47, in search_link
    results = search_widget(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 94, in search_widget
    return frappe.call(
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2530, in wrapper
    return fn(**kwargs)
  File "apps/erpnext/erpnext/controllers/queries.py", line 625, in get_filtered_dimensions
    output = frappe.get_list(
  File "apps/frappe/frappe/__init__.py", line 2039, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 191, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 232, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.UndefinedFunction: operator does not exist: smallint ~~* unknown
LINE 3: ...nter" ilike '%%%%' or "tabCost Center"."is_group" ilike '%%%...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "",
		"doctype": "Cost Center",
		"ignore_user_permissions": 0,
		"reference_doctype": "Sales Invoice",
		"page_length": 10,
		"query": "erpnext.controllers.queries.get_filtered_dimensions",
		"filters": "{\"dimension\":\"cost_center\",\"company\":\"Satya Tech\"}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "UndefinedFunction",
	"_exc_source": "erpnext (app)",
	"_debug_messages": "[\"Error in query:\\noperator does not exist: smallint ~~* unknown\\nLINE 3: ...nter\\\" ilike '%%%%' or \\\"tabCost Center\\\".\\\"is_group\\\" ilike '%%%...\\n                                                             ^\\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.\\n\"]"
}
```
```

**Comment by shyamrathod12** [comment]
resolve the issue

	for field in searchfields:
		field_meta = meta.get_field(field)
		if field_meta and field_meta.fieldtype in ["Data", "Text", "Small Text", "Long Text"]:
			or_filters.append([field, "ILIKE", "%%%s%%" % txt])  # ILIKE for case-insensitive search
			fields.append(field)
change in 
get_filtered_dimensions():
@frappe.whitelist()
@frappe.validate_and_sanitize_search_inputs
def get_filtered_dimensions(doctype, txt, searchfield, start, page_len, filters, reference_doctype=None):
	from erpnext.accounts.doctype.accounting_dimension_filter.accounting_dimension_filter import (
		get_dimension_filter_map,
	)

	dimension_filters = get_dimension_filter_map()
	dimension_filters = dimension_filters.get((filters.get("dimension"), filters.get("account")))
	query_filters = []
	or_filters = []
	fields = ["name"]

	searchfields = frappe.get_meta(doctype).get_search_fields()

	meta = frappe.get_meta(doctype)
	if meta.is_tree and meta.has_field("is_group"):
		query_filters.append(["is_group", "=", 0])

	if meta.has_field("disabled"):
		query_filters.append(["disabled", "!=", 1])

	if meta.has_field("company"):
		query_filters.append(["company", "=", filters.get("company")])

	for field in searchfields:
		field_meta = meta.get_field(field)
		if field_meta and field_meta.fieldtype in ["Data", "Text", "Small Text", "Long Text"]:
			or_filters.append([field, "ILIKE", "%%%s%%" % txt])  # ILIKE for case-insensitive search
			fields.append(field)
	if dimension_filters:
		if dimension_filters["allow_or_restrict"] == "Allow":
			query_selector = "in"
		else:
			query_selector = "not in"

		if len(dimension_filters["allowed_dimensions"]) == 1:
			dimensions = tuple(dimension_filters["allowed_dimensions"] * 2)
		else:
			dimensions = tuple(dimension_filters["allowed_dimensions"])

		query_filters.append(["name", query_selector, dimensions])

	output = frappe.get_list(
		doctype,
		fields=fields,
		filters=query_filters,
		or_filters=or_filters,
		as_list=1,
		reference_doctype=reference_doctype,
	)

	return [tuple(d) for d in set(output)]

**Comment by VishvParikh** [comment]
issue is resolved
code is pushed in the sales_invoicecost_center_error
and pr number link:
https://github.com/8848digital/erpnext/pull/17

**Comment by aasif-patel** [comment]
@VishvParikh please raise another PR for Pre-Prod branch

**Comment by aasif-patel** [comment]
Resolved hence closing...
