### ISSUE TITLE
Bank Reconciliation Tool -Bug

### ISSUE THREAD

**Issue by yatishdarji** [8848digital/erpnext#601]
### Discussed in https://github.com/8848digital/erpnext/discussions/597

<div type='discussions-op-text'>

<sup>Originally posted by **Stan-420** November 11, 2024</sup>
When we select "Internal transfer" in payment entry and make inter bank transactions and when we try to reconcile with the bank statement uploaded, the "Closing balance as per ERP" under bank reconciliation tool should reflect with the same amount that's been reconciled & the difference should reduce by that reconciled amount, howeve, as per the attached image, the "Closing balance as per ERP" is coming "0" even after reconciling which needs to be resolved

![image](https://github.com/user-attachments/assets/42b9a639-3117-441e-8c9a-500335ea80b1)
![image](https://github.com/user-attachments/assets/883654f8-9221-4675-ba79-47393e5e8654)</div>

**Comment by tinadn** [comment]
Resolved. Hence closing.
