### ISSUE TITLE
In the Sales Order, the Shipment Rule selection should be filtered according to the chosen company

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#624]
### Information about bug

![image](https://github.com/user-attachments/assets/b277d75c-2ef8-49a4-8d5e-9d2f0a3944b2)

### Module

selling

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (develop)

sales_commission: v0.0.1 (master)

### Installation method

None

**Comment by shubham-DT** [comment]
issue resolved

**Comment by tinadn** [comment]
Resolved. Hence closing.
