### ISSUE TITLE
Sales return permits multiple returns for the same serial number !

### ISSUE THREAD

**Issue by bharatha24272** [8848digital/erpnext#630]
### Information about bug

The system allows multiple sales returns for the same serial number, even if the product has already been returned.

For example, a customer purchases a serialized product with serial numbers SN001, SN002, and SN003 (total of 3 quantities) in a single sales invoice. The customer later returns one of the products, and the sales return is successfully processed for SN001. However, the system allows the creation of multiple sales returns for the same serial number SN001, even though it has already been returned. This means the same serial number can be returned multiple times, up to the total quantity of the sales invoice, which should not be allowed.

http://3.138.223.54/app/sales-invoice/ACC-SINV-2024-38198

<img width="908" alt="image" src="https://github.com/user-attachments/assets/c1f3b072-aaca-49cc-9f10-6d1bc00324f1">

<img width="887" alt="image" src="https://github.com/user-attachments/assets/3c2d824f-4cf1-4aba-b55f-ce563da53313">

<img width="893" alt="image" src="https://github.com/user-attachments/assets/6e17538e-f9e3-49dc-94cf-97bc71364d0e">

### Module

selling

### Version

Installed Apps
Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

FrappeCloud

**Comment by sibikumarkuppusamy** [comment]
Now it's working fine. 
system throws an error message if the same serial number is returned again.
![image](https://github.com/user-attachments/assets/35ac3682-41d5-4dd3-bbfe-6babf39dca77)

**Comment by tinadn** [comment]
Working fine. Hence closing.
