### ISSUE TITLE
The system allows manual assignment of serial numbers to batched inventory type items, even though "Has Serial No" is disabled.

### ISSUE THREAD

**Issue by bharatha24272** [8848digital/erpnext#631]
### Information about bug

The system allows manual assignment of serial numbers to batched items, which should only be tracked by batch numbers, even though "Has Serial No" is disabled in the item master.

For example, a customer purchases 100 units of a product in a single batch, and the system should assign a batch number (e.g., Batch001) to track all 100 items together. However, the system allows users to manually assign individual serial numbers (e.g., SN001, SN002, etc.) to each unit within the batch, even though "Has Serial No" is disabled in the item master, which should prevent serial number assignment. This is incorrect, as batched items should only be tracked by their batch number, not by individual serial numbers, leading to confusion in inventory management.

**_Item master_**
http://3.138.223.54/app/item/TEST-BATCH-MAN-INV-001
<img width="925" alt="image" src="https://github.com/user-attachments/assets/251a3623-370a-4fff-9065-c928026fd699">

**_Stock Reconciliation_**
http://3.138.223.54/app/stock-reconciliation/MAT-RECO-2024-00064
<img width="924" alt="image" src="https://github.com/user-attachments/assets/3a3e83c5-a686-4216-8108-59bd1bd045e4">

**_Serial and Batch Bundle_**
http://3.138.223.54/app/serial-and-batch-bundle/SABB-00004450
<img width="833" alt="image" src="https://github.com/user-attachments/assets/7d6ed45f-8f61-49bd-a96f-1feb92c4567d">

### Module

stock

### Version

Installed Apps
Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

FrappeCloud

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
