### ISSUE TITLE
Sales taxes and charges not populating during import of Sales order or invoice despite template selection

### ISSUE THREAD

**Issue by bharatha24272** [8848digital/erpnext#643]
### Information about bug

When creating a Sales Order or Invoice manually, the system automatically fills in the Sales Taxes and Charges table once a template is selected. However, during the import process, the table remains blank, even though the template is specified in the import file, and the expected automatic population does not occur.

http://3.138.223.54/app/sales-order/SAL-ORD-2024-09375

<img width="838" alt="image" src="https://github.com/user-attachments/assets/f31e8c30-aeff-4d31-b288-211e375c6e3d">

### Module

selling

### Version

Installed Apps
Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

FrappeCloud

**Comment by tinadn** [comment]
Resolved. Hence closing.
