### ISSUE TITLE
System Error When Unreconciling Payment via Purchase Invoice

### ISSUE THREAD

**Issue by pooja8848** [8848digital/erpnext#645]
### Information about bug

When attempting to unreconcile data through the purchase invoice, a system error occurs. However, the unreconciliation process works as expected when performed via the payment entry

![Unlinking error in invoices](https://github.com/user-attachments/assets/c03658a9-ef34-4389-a638-1e45e2d08446)

### Module

accounts, buying, selling

### Version

15

### Installation method

None

**Comment by pooja8848** [comment]
Please note that this error also occurs when unreconciling or unlinking through the sales invoice.

**Comment by tinadn** [comment]
Resolved. Hence closing.
