### ISSUE TITLE
Service Level Agreement

### ISSUE THREAD

**Issue by arvind8848** [8848digital/erpnext#68]
### Information about bug

While creating service level agreement, under status details section there are 2 fields named as SLA full field on SLA Paused on, after selecting both the field option is not coming on the dropdown menu.

### Module

support

### Version

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by aasif-patel** [comment]
Not reflecting on the server Hence Closing...
