### ISSUE TITLE
During a Stock Entry, when I select the company "French Connection," the system should show only warehouses linked to "French Connection." However, it’s showing warehouses from "PP LTD," which is set as the default in the session.

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#681]
### Information about bug

During a Stock Entry, when I select the company "French Connection," the system should show only warehouses linked to "French Connection." However, it’s showing warehouses from "PP LTD," which is set as the default in the session.

![image](https://github.com/user-attachments/assets/1454ec1f-ff95-4d93-8b51-801783235322)

![image](https://github.com/user-attachments/assets/c8b402db-d1c5-4ced-aa64-5569da1ce07d)

But for Material transfer, for source warehouse it shows only warehouses from PP LTD, and for target warehouse it correctly show only warehouses linked to "French Connection." 
![image](https://github.com/user-attachments/assets/c01a10f8-0012-4cbc-8272-36dba026ddc9)

![image](https://github.com/user-attachments/assets/f539e4a6-990b-4501-bb72-684f7db90e38)

### Module

stock

### Version

ERPNext: v15.35.1 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by Abhishek8848** [comment]
It's working now.
![image](https://github.com/user-attachments/assets/81e56e41-dd0b-4adc-b539-97e331f6c0d4)

**Comment by Purvi8848** [comment]
This issue gets resolved temporarily but keeps happening again. Facing this issue again

**Comment by IamSaiyyamChhetri** [comment]
In my local issue is getting reproduce 

![Screenshot 2024-11-27 at 6 02 01 PM](https://github.com/user-attachments/assets/bd2e9f7c-5943-4c9f-9ec4-877893321900)

**Comment by tinadn** [comment]
Resolved. Hence closing.
