### ISSUE TITLE
Server error while importing contacts

### ISSUE THREAD

**Issue by bharatha24272** [8848digital/erpnext#689]
### Information about bug

Server error while importing contacts.

[Contact (10).csv](https://github.com/user-attachments/files/17844030/Contact.10.csv)

<img width="771" alt="image" src="https://github.com/user-attachments/assets/9c12f909-0e13-4724-9b03-6b03df580e39">

### Module

selling, CRM

### Version

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (master)

ERPNext: v15.35.1 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

FrappeCloud

**Comment by tinadn** [comment]
Resolved. Hence closing.
