### ISSUE TITLE
Opportunity in the Contacts tab: Contact Person Error

### ISSUE THREAD

**Issue by shyamrathod12** [8848digital/erpnext#7]
### Information about bug

when selecting the Contact Person
![Screenshot from 2024-09-04 15-38-36](https://github.com/user-attachments/assets/f31fb299-6026-4036-923e-98c40e668f61)

### Module

CRM

### Version

ERPNext: v15.34.0 (version-15)

Frappe Framework: v15.40.0 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.34.0",
	"frappe": "15.40.0"
}
```
### Route
```
Form/Opportunity/new-opportunity-ecbhiebyqv
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 47, in search_link
    results = search_widget(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 94, in search_widget
    return frappe.call(
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 2530, in wrapper
    return fn(**kwargs)
  File "apps/frappe/frappe/contacts/doctype/contact/contact.py", line 261, in contact_query
    return frappe.db.sql(
  File "apps/frappe/frappe/database/postgres/database.py", line 219, in sql
  File "apps/frappe/frappe/database/database.py", line 230, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: LIMIT #,# syntax is not supported
LINE 15:   limit '0', '10'
           ^
HINT:  Use separate LIMIT and OFFSET clauses.


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "",
		"doctype": "Contact",
		"ignore_user_permissions": 0,
		"reference_doctype": "Opportunity",
		"page_length": 10,
		"query": "frappe.contacts.doctype.contact.contact.contact_query",
		"filters": "{\"link_doctype\":\"Customer\",\"link_name\":\"Test1\"}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "SyntaxError",
	"_debug_messages": "[\"Syntax error in query:\\nselect\\n\\t\\t\\t\\\"tabContact\\\".name, \\\"tabContact\\\".full_name, \\\"tabContact\\\".company_name\\n\\t\\tfrom\\n\\t\\t\\t\\\"tabContact\\\", \\\"tabDynamic Link\\\"\\n\\t\\twhere\\n\\t\\t\\t\\\"tabDynamic Link\\\".parent = \\\"tabContact\\\".name and\\n\\t\\t\\t\\\"tabDynamic Link\\\".parenttype = 'Contact' and\\n\\t\\t\\t\\\"tabDynamic Link\\\".link_doctype = %(link_doctype)s and\\n\\t\\t\\t\\\"tabDynamic Link\\\".link_name = %(link_name)s and\\n\\t\\t\\t\\\"tabContact\\\".\\\"name\\\" like %(txt)s\\n\\t\\t\\t\\n\\t\\torder by\\n\\t\\t\\tif(strpos( \\\"tabContact\\\".full_name, %(_txt)s), strpos( \\\"tabContact\\\".company_name, %(_txt)s), 99999),\\n\\t\\t\\t\\\"tabContact\\\".idx desc, \\\"tabContact\\\".full_name\\n\\t\\tlimit %(start)s, %(page_len)s {'txt': '%%', '_txt': '', 'start': '0', 'page_len': '10', 'link_name': 'Test1', 'link_doctype': 'Customer'}\"]"
}
```
```

**Comment by VishvParikh** [comment]
issue is resolved 
change the contact_query sql in the contact.py  


update the code in contact.py


@frappe.whitelist()
@frappe.validate_and_sanitize_search_inputs
def contact_query(doctype, txt, searchfield, start, page_len, filters):
	from frappe.desk.reportview import get_match_cond

	doctype = "Contact"
	if not frappe.get_meta(doctype).get_field(searchfield) and searchfield not in frappe.db.DEFAULT_COLUMNS:
		return []

	link_doctype = filters.pop("link_doctype")
	link_name = filters.pop("link_name")

	return frappe.db.sql(
		f"""select
			`tabContact`.name, `tabContact`.full_name, `tabContact`.company_name
		from
			`tabContact`, `tabDynamic Link`
		where
			`tabDynamic Link`.parent = `tabContact`.name and
			`tabDynamic Link`.parenttype = 'Contact' and
			`tabDynamic Link`.link_doctype = %(link_doctype)s and
			`tabDynamic Link`.link_name = %(link_name)s and
			`tabContact`.`{searchfield}` like %(txt)s
			{get_match_cond(doctype)}
		order by
			(case when position(%(_txt)s in `tabContact`.full_name) > 0 then position(%(_txt)s in `tabContact`.full_name) when position(%(_txt)s in `tabContact`.company_name) > 0 then position(%(_txt)s in `tabContact`.company_name) else 99999 end),
			`tabContact`.idx desc, `tabContact`.full_name
		limit %(page_len)s offset %(start)s""",
		{
			"txt": "%" + txt + "%",
			"_txt": txt.replace("%", ""),
			"start": start,
			"page_len": page_len,
			"link_name": link_name,
			"link_doctype": link_doctype,
		},
	)

**Comment by VishvParikh** [comment]
issue is resolved
code is pushed in the opportunity_contact_person_error
and pr number link:
https://github.com/Satya8848/frappe-postgres/pull/2

**Comment by aasif-patel** [comment]
@VishvParikh please raise another PR for pre-prod,

**Comment by VishvParikh** [comment]
@aasif-patel  new pr is raised

**Comment by aasif-patel** [comment]
Test and Resolved, Hence closing...
