### ISSUE TITLE
Incorrect outstanding balance on invoices after linking payment 

### ISSUE THREAD

**Issue by pooja8848** [8848digital/erpnext#708]
### Information about bug

"After making a direct payment or linking a payment to an invoice, the invoice status updates to 'Paid,' but the outstanding amount appears incorrect (the paid amount is displayed as negative in the outstanding balance field). As a result, the invoice remains in the list when selecting 'Get Unreconciled Entries in Payment Reconciliation tool.  
![image](https://github.com/user-attachments/assets/6d755332-2559-41f7-a275-18fc07e38afd)
![image](https://github.com/user-attachments/assets/5bc8a4ab-4331-4c2f-a366-5f6e38093a08)

### Module

accounts, buying, selling

### Version

ERPNext: v15.35.1 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
