### ISSUE TITLE
Selected a project in the Purchase Receipt, but it does not appear in the Stock Ledger Report. Additionally, when we attempt to view the project through the connection, the system redirects to a different project.

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#710]
### Information about bug

Selected a project in the Purchase Receipt, but it does not appear in the Stock Ledger Report.
![image](https://github.com/user-attachments/assets/3acd5b80-bfbb-49ef-882b-18e64d4a48c9)

![image](https://github.com/user-attachments/assets/7ee22b13-37c1-475b-97e8-f12b42df951c)

 
Additionally, when we attempt to view the project through the connection, the system redirects to a different project.

![image](https://github.com/user-attachments/assets/69536fdf-71cc-4bf0-9d2c-c528689a8f0c)

![image](https://github.com/user-attachments/assets/3fe7255b-47c4-44c7-8fa5-3eff37e0d001)

### Module

stock

### Version

ERPNext: v15.35.1 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by Abhishek8848** [comment]
It's Working now.
https://postgres-project.8848digitalerp.com/app/purchase-receipt/MAT-PRE-2024-07172
![image](https://github.com/user-attachments/assets/404bd2da-7de8-4662-a872-9e0225884399)

**Comment by tinadn** [comment]
Working fine. Hence closing.
