### ISSUE TITLE
While creating a new item, field for HSN/SAC is missing

### ISSUE THREAD

**Issue by charissa8848** [8848digital/erpnext#721]
### Information about bug

While creating a new item, field for HSN/SAC is missing below 'Item Group'-

![Screenshot 2024-11-26 110245](https://github.com/user-attachments/assets/7cc93897-0c93-464f-9ab8-a87ad050cdf8)

This should be a mandatory field.

### Module

accounts

### Version

Frappe Version: v15.41.0 (pre-prod)

ERPNext: v15.36.2 (pre-prod)

### Installation method

None

**Comment by sibikumarkuppusamy** [comment]
HSN is belongs to India Compliance App.

**Comment by tinadn** [comment]
Resolved. Hence closing.
