### ISSUE TITLE
Error while Importing "Sales Invoice" from Data Import dt

### ISSUE THREAD

**Issue by IamSaiyyamChhetri** [8848digital/erpnext#727]
### Information about bug

URL Site : https://postgres-erpnext.8848digitalerp.com/app/data-import/new-data-import-npkbzhslgd

![Screenshot 2024-11-26 at 12 01 05 PM](https://github.com/user-attachments/assets/810fbe68-8308-48c5-9595-2256336b3f5d)

### Module

other

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by IamSaiyyamChhetri** [comment]
@aasif-patel ,
Issue resolved you can close this issue.
Thank you.

**Comment by aasif-patel** [comment]
Resolved hence closing
