### ISSUE TITLE
When a manual entry for Repost Item Valuation is created, the RQ job status shows "Started," but no further processing occurs, and the task remains incomplete.

### ISSUE THREAD

**Issue by Purvi8848** [8848digital/erpnext#729]
### Information about bug

When a manual entry for Repost Item Valuation is created, the RQ job status shows "Started," but no further processing occurs, and the task remains incomplete.
Due to this unable to check whether system correctly updates stock value.

![image](https://github.com/user-attachments/assets/31a24485-f47c-43ef-95b1-8fe6fb214fa3)

![image](https://github.com/user-attachments/assets/73f29bcd-ccb4-4f73-8ad9-a185bd358c1c)

There is exception
![image](https://github.com/user-attachments/assets/59dfb054-27ab-4aab-b4ef-21d6bfe879ea)

After 26 mins checked again, RQ JOB got failed with exception Work-horse terminated unexpectedly; waitpid returned None; 

![image](https://github.com/user-attachments/assets/47790a95-03d8-4e36-a6c7-8af055056782)

### Module

stock

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by IamSaiyyamChhetri** [comment]
#767

**Comment by tinadn** [comment]
Duplicate issue. Hence closing.
