### ISSUE TITLE
Server error while saving Payment Entry

### ISSUE THREAD

**Issue by charissa8848** [8848digital/erpnext#740]
### Information about bug

I am unable to save the Payment Entry due to a server error-

![image](https://github.com/user-attachments/assets/a8dc3fd6-57c3-48bb-b443-0546fe5ae590)

Pls look into this and resolve asap

### Module

accounts

### Version

Frappe Framework: v15.41.0 (pre-prod)

ERPNext: v15.36.2 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
