### ISSUE TITLE
If the CRM Module is not integrated with core module in HOME page we don’t have to show CRM Doctype.

### ISSUE THREAD

**Issue by Istiyaq8848** [8848digital/erpnext#744]
### Information about bug

If the CRM Module is not integrated with core module in HOME page we don’t have to show CRM Doctype.
![image](https://github.com/user-attachments/assets/10f9dd7e-19f8-43ac-92d4-717669379f3d)

### Module

CRM

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
Na
```

**Comment by tinadn** [comment]
Resolved. Hence closing.
