### ISSUE TITLE
Remove Sales Commission reports

### ISSUE THREAD

**Issue by Istiyaq8848** [8848digital/erpnext#747]
### Information about bug

Remove (Sales Partners Commission & Sales Partner Target Variance Based on Item Group Report) From Selling Module Dashboard. 
![image](https://github.com/user-attachments/assets/d6656442-eaee-4f7b-a9f8-ee109da3ff29)

### Module

selling

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by Prateek8848** [comment]
We can close this 
PR:
https://github.com/8848digital/erpnext/pull/806

**Comment by Prateek8848** [comment]
https://github.com/8848digital/erpnext/pull/816

**Comment by tinadn** [comment]
Resolved. Hence closing.
