### ISSUE TITLE
Removal of Sales Partner Type doctype

### ISSUE THREAD

**Issue by Istiyaq8848** [8848digital/erpnext#748]
### Information about bug

Remove Sales Partner Type list Doctype. It will be included in Sales commission Module 
![image](https://github.com/user-attachments/assets/531efd90-de47-4f06-add6-8f17e414c503)

### Module

selling

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by Prateek8848** [comment]
We can close this PR 
PR:
https://github.com/8848digital/erpnext/pull/810
