### ISSUE TITLE
Error viewing Documents with Supplier Role

### ISSUE THREAD

**Issue by Ankur8848** [8848digital/erpnext#749]
### Information about bug

User provided with just supplier roles & permission facinf the error while viewing RFQ, Supplier Quotations and Purchase Invoices through login.
![image](https://github.com/user-attachments/assets/ad57ea3f-8964-4781-9e96-b6f6355fec43)

### Module

accounts, buying

### Version

ERPNext: v15.36.2 

Frappe Framework: v15.41.0 

### Installation method

None

**Comment by Ankur8848** [comment]
@Abhishek8848 The issue is still there with RFQ. Supplier Quotation and Purchase Invoice is fixed.

**Comment by Abhishek8848** [comment]
@Ankur8848 can you please share the error or reference  of RFQ ?
![image](https://github.com/user-attachments/assets/4e56821f-ab14-49c9-ba74-5a3632b22fe7)
I am not able to see any error or bug.

**Comment by Ankur8848** [comment]
https://postgres-project.8848digitalerp.com/rfq
![image](https://github.com/user-attachments/assets/4fbd79f4-6aa6-4ca1-a371-1346f039cdb4)

**Comment by Ankur8848** [comment]
Working fine now.

**Comment by tinadn** [comment]
Resolved. Hence closing.
