### ISSUE TITLE
Item Price List is not created automatically while saving the PO 

### ISSUE THREAD

**Issue by charissa8848** [8848digital/erpnext#751]
### Information about bug

Item Price List should be created automatically on saving a Purchase Order in case an item is being purchased for the first time. A screenshot has been uploaded of the similar instance performed on my demo site.

![image](https://github.com/user-attachments/assets/338ab166-5efb-43e1-b98b-9bf3cb853ec6)

### Module

accounts

### Version

Frappe Framework: v15.41.0 (pre-prod)

ERPNext: v15.36.2 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
@charissa8848 Enable checkbox in stock setting to auto insert item price
Working fine. Hence closing.
