### ISSUE TITLE
Unable to edit the rows inside the child table in the Journal Entry doctype

### ISSUE THREAD

**Issue by charissa8848** [8848digital/erpnext#755]
### Information about bug

In an already posted journal entry, if I wish to go into and view any of the rows in the 'Accounting Entries' child table, the system does not allow me to do so. Kindly look into it

![image](https://github.com/user-attachments/assets/e6960cd5-9b15-4915-8f28-27e51501431f)

### Module

accounts

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Resolved. Hence closing
