### ISSUE TITLE
Serial numbers not removed after sales return in the item table

### ISSUE THREAD

**Issue by bharatha24272** [8848digital/erpnext#756]
### Information about bug

When a sales invoice is created for 2 items, and 1 item is returned via a sales return, the quantity is updated correctly, leaving 1 item remaining. However, when I create a sales return for the second item, the quantity is updated correctly, but both serial numbers remain in the item table. I am then forced to manually delete the serial number that was already returned (SN001) and proceed with the return for the second item (SN002).

Example:

A sales invoice is created for 2 units of Item A, with serial numbers SN001 and SN002. After returning 1 unit (SN001), the quantity is updated correctly, leaving 1 unit (SN002). However, when creating another sales return for the second unit (SN002), the quantity is updated correctly, but both serial numbers (SN001 and SN002) are still listed in the item table. This forces me to manually delete the serial number SN001, which has already been returned, before proceeding with the return for the second item.

Expected Behavior:

After returning an item (e.g., SN001), I should only be able to select from the remaining quantity (SN002), and the serial numbers of the returned items (SN001) should be automatically removed from the item table.

### Module

selling

### Version

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (master)

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

FrappeCloud

**Comment by bharatha24272** [comment]
https://drive.google.com/drive/folders/1f10K9H4MgvChqOTBtBOZfNYIZ3sMvbW0?usp=sharing

**Comment by tinadn** [comment]
Resolved. Hence closing.
