### ISSUE TITLE
In the Sales Order Analysis report, the Warehouse filter should dynamically display warehouses based on the selected company.

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#760]
### Information about bug

![image](https://github.com/user-attachments/assets/5973cfe9-4d04-4c1d-b02b-bb16f677bf50)

### Module

selling

### Version

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (master)

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

None

**Comment by tinadn** [comment]
Resolved. Hence closing.
