### ISSUE TITLE
In the Sales Order, Delivery Note and Sales Invoice, the Shipment Rule selection should be filtered according to the chosen company

### ISSUE THREAD

**Issue by rushabhmaywade** [8848digital/erpnext#763]
### Information about bug

![image](https://github.com/user-attachments/assets/c70f6084-db45-48a1-baf0-c71eff0fe4c0)

### Module

selling

### Version

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (master)

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

None

**Comment by tinadn** [comment]
Resolved. Hence closing.
