### ISSUE TITLE
Error in VAT Audit Report Doctype

### ISSUE THREAD

**Issue by Ankur8848** [8848digital/erpnext#765]
### Information about bug

https://postgres-project.8848digitalerp.com/app/query-report/VAT%20Audit%20Report
![image](https://github.com/user-attachments/assets/24fe36bb-6bf5-4519-9d68-5b5630210b8b)

### Module

accounts

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by Ankur8848** [comment]
Working well now

**Comment by tinadn** [comment]
Resolved. Hence closing.
