### ISSUE TITLE
Import Data

### ISSUE THREAD

**Issue by Istiyaq8848** [8848digital/erpnext#766]
### Information about bug

While importing the purchase order this is Error is showing. 
![image](https://github.com/user-attachments/assets/af08a262-47b0-4f25-90f9-5990684819d8)

### Module

other

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Resolved. Hence closing.
