### ISSUE TITLE
Supplier Portal

### ISSUE THREAD

**Issue by Istiyaq8848** [8848digital/erpnext#768]
### Information about bug

When created RFQ Supplier is not able to fill the RFQ from the portal. System is allowing the Supplier to Login Properly. But not showing the any RFQ on portal. Showing (Uncaught Server Exception)
![image](https://github.com/user-attachments/assets/2f380a4a-c9ee-422b-8387-36d6b94c8eb0)

### Module

buying

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Resolved. Hence closing.
