### ISSUE TITLE
System allows import and submission of Quotations, Sales orders, Sales invoices, and Delivery notes with incorrect Item tax templates

### ISSUE THREAD

**Issue by bharatha24272** [8848digital/erpnext#770]
### Information about bug

The system is allowing the import and submission of quotations, sales orders, sales invoices, and delivery notes with incorrect Item Tax Templates if an Item Tax Template from another company is specified in the import file for testing purposes, even though the correct company is specified in the file.

https://drive.google.com/file/d/17niRlkDaPp5gT6HSNp4dx1ihixn0NXTy/view?usp=sharing

_**Example:**_
An import file is created for Company A, correctly specifying Company A. However, an Item Tax Template belonging to Company B is intentionally included to test how the system behaves with mismatched templates. This issue can occur with quotations, sales orders, sales invoices, or delivery notes.

**Expected behavior:**
The system should reject the import if an incorrect Item Tax Template is provided.

**Actual behavior:**
The system allows the import and submission of the quotation, sales order, sales invoice, or delivery note, applying the Item Tax Template from Company B, despite Company A being specified in the import file.

https://postgres-project.8848digitalerp.com/app/quotation/SAL-QTN-2024-00173
[SQ Data Import - Test-Sales Tax - 002.csv](https://github.com/user-attachments/files/17948549/SQ.Data.Import.-.Test-Sales.Tax.-.002.csv)

https://postgres-project.8848digitalerp.com/app/sales-order/SAL-ORD-2024-09491
[SO Data Import - Test-Sales Tax - 002.csv](https://github.com/user-attachments/files/17948550/SO.Data.Import.-.Test-Sales.Tax.-.002.csv)

https://postgres-project.8848digitalerp.com/app/sales-invoice/ACC-SINV-2024-51228
[SI Data Import - Test-Sales Tax - 002.csv](https://github.com/user-attachments/files/17948559/SI.Data.Import.-.Test-Sales.Tax.-.002.csv)

https://postgres-project.8848digitalerp.com/app/delivery-note/MAT-DN-2024-03833
[DN Data Import - Test-Sales Tax - 002.csv](https://github.com/user-attachments/files/17948561/DN.Data.Import.-.Test-Sales.Tax.-.002.csv)

### Module

selling

### Version

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (master)

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

FrappeCloud

**Comment by tinadn** [comment]
@sibikumarkuppusamy Connect with @bharatha24272 for this issue

**Comment by tinadn** [comment]
Resolved. Hence closing.
