### ISSUE TITLE
System Allows Recording Multicurrency Transactions Against INR Payable/Receivable Account

### ISSUE THREAD

**Issue by pooja8848** [8848digital/erpnext#793]
### Information about bug

When recording a purchase or sale transaction involving a supplier or customer dealing in a foreign currency (e.g., USD), and no default payable/receivable account in the respective currency (USD) is linked to the supplier/customer, the system allows the transaction to be recorded against an INR payable/receivable account, instead of triggering an error as expected.

Error Message that should Pop Up
![image](https://github.com/user-attachments/assets/5a163d20-5b87-4f49-b41f-02d5abe4ee12)

USD Currency Transaction getting recorded against INR Creditors account
![image](https://github.com/user-attachments/assets/81954da7-e0ae-493f-94dc-1fb964bcacbe)

![image](https://github.com/user-attachments/assets/b47533ee-999b-4d28-b8be-5444495adc06)

### Module

accounts, buying, selling

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by pooja8848** [comment]
Its working now, issue can be closed

**Comment by tinadn** [comment]
Resolved. Hence closing.
