### ISSUE TITLE
Server error in auto reconciliation and manual bank reconciliation

### ISSUE THREAD

**Issue by charissa8848** [8848digital/erpnext#794]
### Information about bug

While auto reconciling as well as while performing manual reconciliation of  the transactions, the system throws a server error-

![image](https://github.com/user-attachments/assets/099c6121-a691-41f1-b0aa-69281c103592)

### Module

accounts

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
