### ISSUE TITLE
GSTIN details not fetching automatically

### ISSUE THREAD

**Issue by bharatha24272** [8848digital/erpnext#800]
### Information about bug

When creating a Supplier/Customer and entering a valid GSTIN, the system should automatically fetch details like name and address, but this is not happening. Please refer to the video created for further clarification.

https://drive.google.com/file/d/1cuLXjob8t0i3nkGBVuYMG6ih3Z5rHX0X/view?usp=sharing

### Module

buying, selling

### Version

Apnaklub Mobile App: v0.0.1 (main)

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (pre-prod)

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

India Compliance: v15.14.2 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (pre-prod)

sales_commission: v0.0.1 (master)

### Installation method

FrappeCloud

**Comment by anandk-spyke-o1** [comment]
Please enable the API features from GST Settings and then the issue will get resolved.
![Screenshot from 2024-12-03 19-34-15](https://github.com/user-attachments/assets/3baf6387-fa7d-459f-a4bc-4f69a0ffc9da)

If you enable the API Features with a valid GSTIN number then it will store an API key and secret in the GST Settings tab inside some hidden fields. And these API key and secrets will be used to make further API calls. A use case of this is - "if GSTIN provided make an API call to fetch other GSTIN Info." by get_gstin_info API.
![Screenshot from 2024-12-03 19-37-31](https://github.com/user-attachments/assets/7b0b3348-84cf-4b93-bf49-84aaca246149)

**Comment by bharatha24272** [comment]
I tried enabling it, but it's asking for an Email ID and GSTIN. Can you please check from your side?

![image](https://github.com/user-attachments/assets/2d1713d1-7a01-42d8-a594-c2f9faadcadd)

![image](https://github.com/user-attachments/assets/3e8e4aa4-954a-419b-ba3f-74090e7a839b)

**Comment by anandk-spyke-o1** [comment]
Additionally, Sandbox Mode checkbox should be disabled then it will fetch the customer details based on GSTIN. 
![Screenshot from 2024-12-09 13-52-52](https://github.com/user-attachments/assets/2600294a-6e55-4104-ad70-6438eac8dc52)

Now I have disabled it on the apnaklub instance and I have foud that customer details are fetching.

Source code snippet lies in India Compliance app inside quick_entry.js file.
![Screenshot from 2024-12-09 13-57-01](https://github.com/user-attachments/assets/a2cce68a-633d-4614-8dcc-cc02b0b580f9)

**Comment by tinadn** [comment]
Resolved. Hence closing
