### ISSUE TITLE
Duplicate exchange differences journal entries are being recorded on multicurrency transactions during the payment reconciliation process.

### ISSUE THREAD

**Issue by pooja8848** [8848digital/erpnext#801]
### Information about bug

When reconciling a foreign currency invoice with a payment entry, the system is expected to record any exchange difference through a journal entry. Currently, the system is processing this correctly by recording the exchange difference. However, the issue is that the system is duplicating the previously recorded exchange difference, leading to an incorrect entry.

We need the system to ensure that it only records the exchange difference once, without duplicating any previous entries.

![image](https://github.com/user-attachments/assets/19017005-866b-4f72-83f5-6c5223e28a03)

### Module

accounts, buying, selling

### Version

ERPNext: v15.38.4 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Resolved. Hence closing.
