### ISSUE TITLE
Job Card Not Subitting

### ISSUE THREAD

**Issue by Istiyaq8848** [8848digital/erpnext#805]
### Information about bug

While submitting the Job Card When i click on Completed Job and try to submit. System is not allowing to Submit the Doctype. No Error is shown
![image](https://github.com/user-attachments/assets/37c1adda-af9a-43f0-8e17-5675f56f4065)

### Module

manufacturing

### Version

ERPNext: v15.36.2 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Working fine. Hence closing.
