### ISSUE TITLE
getting error while creating purchase invoice

### ISSUE THREAD

**Issue by akshata170820** [8848digital/erpnext#836]
### Information about bug

![Screenshot 2024-12-12 153220](https://github.com/user-attachments/assets/9844aec8-ffec-42f0-9ff4-5c3f2088868e)

### Module

stock

### Version

v15.44.0 
 v15.48.1 

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
^
Possible source of error: erpnext (app)
```

**Comment by Abhishek8848** [comment]
It's working now.

**Comment by tinadn** [comment]
resolved. Hence closing.
