### ISSUE TITLE
Filters in the "Procurement Tracker" report are not being applied correctly based on the selected company.

### ISSUE THREAD

**Issue by bharatha24272** [8848digital/erpnext#840]
### Information about bug

The filters in the "Procurement Tracker" report are not being applied correctly based on the selected company.

For example, when selecting Company A, the drop-down still displays cost centers and projects associated with Company B.

![image](https://github.com/user-attachments/assets/95d584e8-bf0e-428f-8ed0-6e412e220ff6)

------------------------------
![image](https://github.com/user-attachments/assets/99966f90-9f8f-423d-82d5-7a1b0a04a412)
![image](https://github.com/user-attachments/assets/44babc26-a3b7-48cc-9436-4711d1db1b12)

### Module

buying

### Version

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (master)

ERPNext: v15.38.4 (pre-prod)

Frappe Framework: v15.45.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

FrappeCloud

**Comment by tinadn** [comment]
Resolved. Hence closing.
