### ISSUE TITLE
Incorrect material request status and stock transfer behavior: Material request status stays "Pending" after both partial and full transfers, and Stock transfer allows additional units beyond the maximum limit

### ISSUE THREAD

**Issue by bharatha24272** [8848digital/erpnext#853]
### Information about bug

When a Material Request is created for 10 units with the purpose set to "Material Transfer" and a Stock Entry is made for 5 units, the status of the Material Request should change to "Partially Ordered." However, in the current system, it remains "Pending."

When creating another Stock Transfer for the remaining 5 units against the same Material Request, the transfer quantity incorrectly shows 10 units, even though 5 units have already been transferred. Even after manually updating the quantity to 5 units and submitting it, the Material Request status remains "Pending" instead of updating to "Transferred," as all 10 units have been transferred.

Additionally, the system still allows the creation of Stock Transfers for additional units under the same Material Request, which should not be permitted since the maximum units to be transferred (10) have already been transferred.

Video clip explaining the same,
https://drive.google.com/file/d/1lw4rLMsq8ADLPyVsiC1S7a1ioLnl3VW0/view?usp=sharing

https://postgres-project.8848digitalerp.com/app/material-request/MAT-MR-2024-17500

### Module

stock

### Version

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (master)

ERPNext: v15.45.4 (pre-prod)

Frappe Framework: v15.50.0 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

FrappeCloud

**Comment by tinadn** [comment]
Issue resolved. Hence closing.
