### ISSUE TITLE
GL Closing Feature not working

### ISSUE THREAD

**Issue by Ankur8848** [8848digital/erpnext#858]
### Information about bug

GL Closing feature not working.
Entries can still be made on GLs closed for that particular period of time.
This activity can be done even by the users who do not have the permission to do that.
Kindly fix this.

### Module

accounts, stock, buying, selling, assets

### Version

ERPNext: v15.45.4 (pre-prod)

Frappe Framework: v15.50.0 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Working fine. Hence closing.
