### ISSUE TITLE
patch query error

### ISSUE THREAD

**Issue by aasif-patel** [8848digital/erpnext#861]
### Information about bug

File path:- https://github.com/8848digital/erpnext/blob/pre-prod/erpnext/patches/v14_0/update_stock_uom_in_work_order_item.py

Query in above patch causing issue in migration.

![image](https://github.com/user-attachments/assets/061d800f-59af-4f91-95dd-be185172ebf1)

### Module

selling

### Version

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (master)

ERPNext: v15.45.4 (pre-prod)

Frappe Framework: v15.50.0 (pre-prod)

India Compliance: v15.14.2 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

manual install

**Comment by tinadn** [comment]
Resolved. Hence closing.
