### ISSUE TITLE
Server error while creating Product Bundle

### ISSUE THREAD

**Issue by bharatha24272** [8848digital/erpnext#863]
### Information about bug

Server error while creating product bundle

![image](https://github.com/user-attachments/assets/52c85892-116b-4d8e-b2ef-6a20654bbecf)

### Module

stock

### Version

Assets: v0.0.1 (pre-prod)

CRM: v0.0.1 (master)

ERPNext: v15.45.4 (pre-prod)

Frappe Framework: v15.50.0 (pre-prod)

India Compliance: v15.14.2 (pre-prod)

Payments: v0.0.1 (version-15)

Projects: v0.0.1 (master)

sales_commission: v0.0.1 (master)

### Installation method

FrappeCloud

**Comment by tinadn** [comment]
Resolved. Hence closing.
