### ISSUE TITLE
New Request for Quotation: Page Not loading

### ISSUE THREAD

**Issue by Nisha8848** [8848digital/erpnext#873]
### Information about bug

Site has no information about the **Request for quotation** Doctype. On loading it shows blank completely. 

<img width="956" alt="Bug" src="https://github.com/user-attachments/assets/44d2971b-1055-44d7-8bbb-3511e6fb7626" />

### Module

buying

### Version

ERPNext: v15.46.1 (pre-prod)

Frappe Framework: v15.50.1 (pre-prod)

### Installation method

None

**Comment by tinadn** [comment]
Resolved. Hence closing.
